DataTrain$SubsectionName[DataTrain$SubsectionName=="Asia Pacific"]=""
DataTest$SubsectionName[DataTest$SubsectionName=="Asia Pacific"]=""
DataTrain$NewsDesk[DataTrain$NewsDesk=="Culture"] = ""
DataTest$NewsDesk[DataTest$NewsDesk=="Culture"] = ""
DataTrain$NewsDesk[DataTrain$NewsDesk=="National"] = ""
DataTest$NewsDesk[DataTest$NewsDesk=="National"] = ""
DataTrain$SectionName[DataTrain$SectionName=="World"] = ""
DataTest$SectionName[DataTest$SectionName=="World"] = ""
DataTrain$NewsDesk[DataTrain$NewsDesk=="Travel"] = ""
DataTest$NewsDesk[DataTest$NewsDesk=="Travel"] = ""

DataTrain$daili = as.logical(DataTrain$daili)
DataTrain$archiv = as.logical(DataTrain$archiv)
DataTrain$articl = as.logical(DataTrain$articl)
DataTrain$bank = as.logical(DataTrain$bank)
DataTrain$can = as.logical(DataTrain$can)
DataTrain$compani = as.logical(DataTrain$compani)
DataTrain$day = as.logical(DataTrain$day)
DataTrain$execut = as.logical(DataTrain$execut)
DataTrain$first = as.logical(DataTrain$first)
DataTrain$fashion = as.logical(DataTrain$fashion)
DataTrain$herald = as.logical(DataTrain$herald)
DataTrain$intern = as.logical(DataTrain$intern)
DataTrain$like = as.logical(DataTrain$like)
DataTrain$look = as.logical(DataTrain$look)
DataTrain$make = as.logical(DataTrain$make)
DataTrain$new = as.logical(DataTrain$new)
DataTrain$obama = as.logical(DataTrain$obama)
DataTrain$offer = as.logical(DataTrain$offer)
DataTrain$one = as.logical(DataTrain$one)
DataTrain$photo = as.logical(DataTrain$photo)
DataTrain$presid = as.logical(DataTrain$presid)
DataTrain$report = as.logical(DataTrain$report)
DataTrain$said = as.logical(DataTrain$said)
DataTrain$say = as.logical(DataTrain$say)
DataTrain$senat = as.logical(DataTrain$senat)
DataTrain$share = as.logical(DataTrain$share)
DataTrain$show = as.logical(DataTrain$show)
DataTrain$state = as.logical(DataTrain$state)
DataTrain$today = as.logical(DataTrain$today)
DataTrain$take = as.logical(DataTrain$take)
DataTrain$time= as.logical(DataTrain$time)
DataTrain$tribun = as.logical(DataTrain$tribun)
DataTrain$two = as.logical(DataTrain$two)
DataTrain$unit = as.logical(DataTrain$unit)
DataTrain$will = as.logical(DataTrain$will)
DataTrain$work = as.logical(DataTrain$work)
DataTrain$world = as.logical(DataTrain$world)
DataTrain$week = as.logical(DataTrain$week)
DataTrain$year = as.logical(DataTrain$year)
DataTrain$york = as.logical(DataTrain$york)

DataTest$daili = as.logical(DataTest$daili)
DataTest$archiv = as.logical(DataTest$archiv)
DataTest$articl = as.logical(DataTest$articl)
DataTest$bank = as.logical(DataTest$bank)
DataTest$can = as.logical(DataTest$can)
DataTest$compani = as.logical(DataTest$compani)
DataTest$day = as.logical(DataTest$day)
DataTest$execut = as.logical(DataTest$execut)
DataTest$first = as.logical(DataTest$first)
DataTest$fashion = as.logical(DataTest$fashion)
DataTest$herald = as.logical(DataTest$herald)
DataTest$intern = as.logical(DataTest$intern)
DataTest$like = as.logical(DataTest$like)
DataTest$look = as.logical(DataTest$look)
DataTest$make = as.logical(DataTest$make)
DataTest$new = as.logical(DataTest$new)
DataTest$obama = as.logical(DataTest$obama)
DataTest$offer = as.logical(DataTest$offer)
DataTest$one = as.logical(DataTest$one)
DataTest$photo = as.logical(DataTest$photo)
DataTest$presid = as.logical(DataTest$presid)
DataTest$report = as.logical(DataTest$report)
DataTest$said = as.logical(DataTest$said)
DataTest$say = as.logical(DataTest$say)
DataTest$senat = as.logical(DataTest$senat)
DataTest$share = as.logical(DataTest$share)
DataTest$show = as.logical(DataTest$show)
DataTest$state = as.logical(DataTest$state)
DataTest$today = as.logical(DataTest$today)
DataTest$take = as.logical(DataTest$take)
DataTest$time= as.logical(DataTest$time)
DataTest$tribun = as.logical(DataTest$tribun)
DataTest$two = as.logical(DataTest$two)
DataTest$unit = as.logical(DataTest$unit)
DataTest$will = as.logical(DataTest$will)
DataTest$work = as.logical(DataTest$work)
DataTest$world = as.logical(DataTest$world)
DataTest$week = as.logical(DataTest$week)
DataTest$year = as.logical(DataTest$year)
DataTest$york = as.logical(DataTest$york)


HYP8_3_2_3_2_Model <- svm(as.factor(Popular) ~ . -herald -tribun -two -archiv -unit -photo -work -world, data=DataTrain, type = "C-classification", probability=TRUE, kernel = "polynomial",degree=2,cost=0.2,  gamma = 2, coef0 = 0)

#HYP8_3_2_3_2_predictions = predict(HYP8_3_2_3_2_Model, newx=x[,1],s=c(0.001,0.003), type="response")
HYP8_3_2_3_2_predictions = predict(HYP8_3_2_3_2_Model, DataTrain,decision.values = TRUE, probability = TRUE)
#table(y[,1],HYP8_3_2_3_2_predictions[,1] >0.5)
HYP8_3_2_3_2_ROCRpred = prediction(attr(HYP8_3_2_3_2_predictions, "prob")[,1], DataTrain$Popular)
HYP8_3_2_3_2_ROCRperf = performance(HYP8_3_2_3_2_ROCRpred, "tpr", "fpr")
plot(HYP8_3_2_3_2_ROCRperf, colorize=TRUE, print.cutoffs.at=seq(0,1,0.1), text.adj=c(-0.2,1.7))
HYP8_3_2_3_2_AUC = as.numeric(performance(HYP8_3_2_3_2_ROCRpred, "auc")@y.values)
HYP8_3_2_3_2_AUC

HYP8_3_2_3_2_TestPredictions = predict(HYP8_3_2_3_2_Model, newdata=DataTest,decision.values = TRUE, probability = TRUE)
HYP8_3_2_3_2_Submission = data.frame(UniqueID = NewsTest$UniqueID, Probability1 =attr(HYP8_3_2_3_2_TestPredictions,"prob")[,1])
write.csv(HYP8_3_2_3_2_Submission, "HYP8_3_2_3_2_Submission.csv", row.names=FALSE)

